openapi: 3.0.3
info:
    title: AI News Mailer
    description: A REST service to interact with an emailer that sends AI-summarised news
    version: "1.0"
servers:
    - url: http://localhost:8888
paths:
    /api/email:
        post:
            tags:
                - email
            summary: sendOneEmail email
            description: Send an email to the target subscription
            operationId: email#sendOneEmail
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateOneRequestBody'
                        example:
                            createdAt: "2012-04-23T18:25:43.511Z"
                            email: user@email.com
                            name: John Doe
                            uid: abcd1234
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'SubscriptionFieldMissing: Error returned when the subscription has missing field(s)'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'ServerError: Error returned when there is an internal server error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/subscriptions:
        get:
            tags:
                - subscription
            summary: getAll subscription
            description: Get all subscriptions
            operationId: subscription#getAll
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Subscription'
                                description: A list of subscriptions
                                example:
                                    - createdAt: "2012-04-23T18:25:43.511Z"
                                      email: user@email.com
                                      name: John Doe
                                      uid: abcd1234
                                    - createdAt: "2012-04-23T18:25:43.511Z"
                                      email: user@email.com
                                      name: John Doe
                                      uid: abcd1234
                                    - createdAt: "2012-04-23T18:25:43.511Z"
                                      email: user@email.com
                                      name: John Doe
                                      uid: abcd1234
                            example:
                                - createdAt: "2012-04-23T18:25:43.511Z"
                                  email: user@email.com
                                  name: John Doe
                                  uid: abcd1234
                                - createdAt: "2012-04-23T18:25:43.511Z"
                                  email: user@email.com
                                  name: John Doe
                                  uid: abcd1234
                "500":
                    description: 'ServerError: Error returned when there is an internal server error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - subscription
            summary: createOne subscription
            description: Create a new subscription
            operationId: subscription#createOne
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateOneRequestBody'
                        example:
                            createdAt: "2012-04-23T18:25:43.511Z"
                            email: user@email.com
                            name: John Doe
                            uid: abcd1234
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Subscription'
                            example:
                                createdAt: "2012-04-23T18:25:43.511Z"
                                email: user@email.com
                                name: John Doe
                                uid: abcd1234
                "400":
                    description: 'SubscriptionFieldMissing: Error returned when the subscription has missing field(s)'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "409":
                    description: 'SubscriptionAlreadyExists: Error returned when the subscription already exists'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'ServerError: Error returned when there is an internal server error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/subscriptions/{uid}:
        delete:
            tags:
                - subscription
            summary: deleteOneByUID subscription
            description: Delete a subscription by UID
            operationId: subscription#deleteOneByUID
            parameters:
                - name: uid
                  in: path
                  description: UID of subscription
                  required: true
                  schema:
                    type: string
                    description: UID of subscription
                    example: abcd1234
                  example: abcd1234
            responses:
                "200":
                    description: OK response.
                "404":
                    description: 'SubscriptionNotFound: Error returned when the specified subscription does not exist'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'ServerError: Error returned when there is an internal server error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        get:
            tags:
                - subscription
            summary: getOneByUID subscription
            description: Get a subscription by UID
            operationId: subscription#getOneByUID
            parameters:
                - name: uid
                  in: path
                  description: UID of subscription
                  required: true
                  schema:
                    type: string
                    description: UID of subscription
                    example: abcd1234
                  example: abcd1234
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Subscription'
                            example:
                                createdAt: "2012-04-23T18:25:43.511Z"
                                email: user@email.com
                                name: John Doe
                                uid: abcd1234
                "404":
                    description: 'SubscriptionNotFound: Error returned when the specified subscription does not exist'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'ServerError: Error returned when there is an internal server error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        CreateOneRequestBody:
            type: object
            properties:
                createdAt:
                    type: string
                    description: Datetime when the subscription was made
                    example: "2012-04-23T18:25:43.511Z"
                email:
                    type: string
                    description: Subscribed email
                    example: user@email.com
                name:
                    type: string
                    description: Name of the subscriber
                    example: John Doe
                uid:
                    type: string
                    description: Unique identifier of subcription
                    example: abcd1234
            description: Subscription to be created
            example:
                createdAt: "2012-04-23T18:25:43.511Z"
                email: user@email.com
                name: John Doe
                uid: abcd1234
            required:
                - email
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: true
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: true
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            description: Error returned when there is an internal server error
            example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        Subscription:
            type: object
            properties:
                createdAt:
                    type: string
                    description: Datetime when the subscription was made
                    example: "2012-04-23T18:25:43.511Z"
                email:
                    type: string
                    description: Subscribed email
                    example: user@email.com
                name:
                    type: string
                    description: Name of the subscriber
                    example: John Doe
                uid:
                    type: string
                    description: Unique identifier of subcription
                    example: abcd1234
            description: Representation of the subscription
            example:
                createdAt: "2012-04-23T18:25:43.511Z"
                email: user@email.com
                name: John Doe
                uid: abcd1234
tags:
    - name: subscription
      description: The subscription service provides ways to manage news subscription
    - name: email
      description: The email service allow sending of news email through API
